setup_travis
min_fastlane_version("2.71.0")
default_platform(:ios)

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    ensure_xcode_version(version: "9.2")
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sync_code_signing(type: "appstore")

    increment_build_number(
        build_number: latest_testflight_build_number + 1
    )
    build_app(scheme: "CoinResults Release")
    upload_to_testflight
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    sync_code_signing(type: "appstore")
    capture_screenshots
    build_app(scheme: "CoinResults Release") # more options available
    upload_to_app_store(force: true)
    # frame_screenshots
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
