setup_travis
min_fastlane_version("2.71.0")
default_platform(:ios)

platform :ios do
 lane :beta do
    sync_code_signing(type: "adhoc")
    increment_build_number(xcodeproj: "CoinResults.xcodeproj")
    build_app(scheme: "CoinResults Release")
    hockey(
      api_token: "4895779019194f00ab55bd63773ee10c",
      ipa: "./CoinResults.ipa",
    )
  end

  lane :release do
    sync_code_signing(type: "appstore")
    increment_build_number(xcodeproj: "CoinResults.xcodeproj")
    build_app(scheme: "CoinResults Release")
    capture_screenshots
    upload_to_app_store(force: true)
  end
end
